--- 
- 
  hosts: routers
  name: "General Config"
  tasks: 
    - name: "Add Banner"
      ios_banner: 
        banner: login
        state: present
        text: "This device is managed by ccanda"
      
    - name: "Add Loopback"
      ios_interface: 
        name: Loopback1
        state: present
      