--- 
- 
  hosts: routers
  name: "General Config"
  tasks: 
    - 
      ios_banner: 
        banner: login
        state: present
        text: "This device is managed by ccanda"
      name: "Add Banner"
    - 
      ios_interface: 
        name: Loopback1
        state: present
      name: "Add Loopback"